### ISSUE TITLE
Doesn't work the way it should on orientation change. 

### ISSUE THREAD

**Issue by zeroCoder1** [TeehanLax/UIKit-Dynamics-Example#2]
![ios simulator screen shot 23-sep-2013 12 56 54 pm](https://f.cloud.github.com/assets/1282078/1189741/9ce4728c-2421-11e3-9209-a4f311bfd480.png)

I am trying to fix it. Will update here once it is done.

**Comment by SpaceTrucker2196** [comment]
yep same issue. Did you find a resolution?

**Comment by SpaceTrucker2196** [comment]
see pull request: https://github.com/TeehanLax/UIKit-Dynamics-Example/pull/3
